---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 056984472572.dkr.ecr.us-east-1.amazonaws.com/showmikb:latest
          ports:
            - containerPort: 3000